package config

func Default() Config {
	cfg := Config{
		App: AppConfig{
			Name:       "snablr",
			LogLevel:   "info",
			BannerPath: "internal/ui/assets/snablr.txt",
		},
		Scan: ScanConfig{
			Share:                      nil,
			ExcludeShare:               nil,
			Path:                       nil,
			ExcludePath:                nil,
			Profile:                    "default",
			MaxDepth:                   0,
			WorkerCount:                0,
			MaxFileSize:                10 * 1024 * 1024,
			NoLDAP:                     false,
			Domain:                     "",
			DomainController:           "",
			BaseDN:                     "",
			LDAPAuth:                   "auto",
			LDAPTransport:              "auto",
			DiscoverDFS:                false,
			PrioritizeADShares:         true,
			OnlyADShares:               false,
			Baseline:                   "",
			MaxScanTime:                "",
			CheckpointFile:             "",
			Resume:                     false,
			SkipReachabilityCheck:      false,
			ReachabilityTimeoutSeconds: 3,
			SMBOperationTimeoutSeconds: 30,
		},
		Archives: ArchiveConfig{
			Enabled:                  true,
			AutoZIPMaxSize:           10 * 1024 * 1024,
			AllowLargeZIPs:           false,
			MaxZIPSize:               10 * 1024 * 1024,
			AutoTARMaxSize:           10 * 1024 * 1024,
			AllowLargeTARs:           false,
			MaxTARSize:               10 * 1024 * 1024,
			MaxMembers:               64,
			MaxMemberBytes:           512 * 1024,
			MaxTotalUncompressed:     4 * 1024 * 1024,
			InspectExtensionlessText: true,
		},
		WIM: WIMConfig{
			Enabled:        true,
			AutoWIMMaxSize: 128 * 1024 * 1024,
			AllowLargeWIMs: false,
			MaxWIMSize:     128 * 1024 * 1024,
			MaxMembers:     8,
			MaxMemberBytes: 1024 * 1024,
			MaxTotalBytes:  4 * 1024 * 1024,
		},
		SQLite: SQLiteConfig{
			Enabled:            true,
			AutoDBMaxSize:      5 * 1024 * 1024,
			AllowLargeDBs:      false,
			MaxDBSize:          5 * 1024 * 1024,
			MaxTables:          8,
			MaxRowsPerTable:    5,
			MaxCellBytes:       256,
			MaxTotalBytes:      16 * 1024,
			MaxInterestingCols: 4,
		},
		Suppression: SuppressionConfig{
			File:        "",
			SampleLimit: 10,
			Rules:       nil,
		},
		Rules: RulesConfig{
			Directory:     "",
			FailOnInvalid: false,
		},
		Output: OutputConfig{
			Format:            "console",
			JSONOut:           "results.json",
			HTMLOut:           "report.html",
			CSVOut:            "",
			MDOut:             "",
			CredsOut:          "",
			ScannedTargetsOut: "scanned_targets.txt",
			Pretty:            true,
		},
	}
	applyPathContext(&cfg, "")
	return cfg
}
